### ISSUE TITLE
ヒープ破壊疑惑

### ISSUE THREAD

**Issue by zurachu** [zurachu/pceth2#23]
長いこと稼働していると、SEにノイズが乗ったり、スクリプトが化けたりすることがあった。
USB接続実行で確認。SD実行ではまだ試していない。
現象が発生した少し前でセーブして、アプリ再起動してロードした時は発生しなかった。
ヒープが破壊されているのではないかと思うが、原因は不明。

**Comment by nsawa** [comment]
僕も試してみたのですが、再現出来ませんでした・・・

□環境
・最新リリースの、pceth2 v1.04を使いました。
・ufesvrwでUSB接続で実行しました。
・P/ECEは無改造版です。
・Win10 64bit、Core i7 4500Uです。

□試した手順
・ゲームを起動後、途中で一度もセーブせずに、エンディングまで通しでプレイしました。
・選択肢は全部一番下の選択肢を選びました。

□結果
・BGMもスクリプトも特に問題なく、エンディングまで行って、タイトルに戻りました。
　(ほとんど早送りでプレイしたので、もし細かなスクリプトの文字化けとかでしたら、見落としている可能性がありますが…)

※「SEにノイズが乗ったり」というのはBGMの事でしょうか?(SEは無いと思うので)


---
環境依存か、または何か特定の条件で再現するのかも？と思いました。
また何か気づいたら、ご連絡します。

**Comment by zurachu** [comment]
@nsawa SE 入っていないでしょうか？
こちらでは、想定される変換の流れに合わせてるつもりで手動でゲームデータを固めているので、もしかしたら実際の変換にはエラーがあるかもしれないですね。

SE乗ってる環境で確認していると、多分ヒープ断片化（pceHeapGetMaxFreeSize() 表示しながら実行していたら 2280 まで低下していることがあった）で読み込みに失敗しての問題ではないかと思いましたので、極力断片化しないようにしていきます。
具体的には、
* サイズ上限がある程度見えている pmd は読み込み先をヒープ→4KBの固定バッファに変更
* ヒープの確保順（解放は逆順）が必ずEVScript→Script→SEの順になるようにする

**Comment by nsawa** [comment]
すみません、SEは無いと思い込んでいたので、早送りで飛ばしていたかも知れません。

「SEが鳴るのが確認しやすい箇所」を、教えて頂けませんでしょうか。(できればなるべく序盤で…)
僕が飛ばしていたのか、又は、本当に鳴っていないのか、確認してみようと思います。

**Comment by zurachu** [comment]
@nsawa 冒頭から、目覚まし時計の音が鳴るはずなので、それだと多分鳴っていないのだと思います・・・。

**Comment by nsawa** [comment]
SEの箇所、教えていただいて有難うございます。
はい、目覚まし時計の音、鳴っていないみたいでした。⇒添付動画
[20170723_145041.ZIP](https://github.com/zurachu/pceth2/files/1167887/20170723_145041.ZIP)

もう一度、データ変換してみます。

**Comment by zurachu** [comment]
ゲームデータ（par）にSE_xxxx.ppdが含まれているかどうかと、あと可能であればmk.batの中のコマンドを一つずつ実行してみていただけると幸いです。
これは別のissue建てないといけないかもしれないですね。

**Comment by nsawa** [comment]
念のためもう一度データ変換しなおしてみました。
SE_xxxx.ppdは含まれていないみたいです。⇒添付リスト
[pceth2.zip](https://github.com/zurachu/pceth2/files/1167893/pceth2.zip)


mk.batの中のコマンドを一つずつ実行の件、了解しました。試してみます。

**Comment by nsawa** [comment]
一つづつコマンドを実行した所、途中でエラーが出ていました。⇒添付ログ
'pceth2_20170720.zip'の中にmakefile.soundが不足しているか、又は、自動生成に失敗しているのかなと思いました。
[error.txt](https://github.com/zurachu/pceth2/files/1167914/error.txt)


あと、mk.batを実行したPCにmake.exeが無い場合、別のエラーになるおそれもあるかな、と思いました。
(P/ECE開発環境にPATHが通っていればmakeもあるはずなので杞憂かな・・・一応、念のため)
