### ISSUE TITLE
ゲームデータにSEが格納されない

### ISSUE THREAD

**Issue by zurachu** [zurachu/pceth2#25]
https://github.com/zurachu/pceth2/issues/23#issuecomment-317232903

> 一つづつコマンドを実行した所、途中でエラーが出ていました。⇒添付ログ
> 'pceth2_20170720.zip'の中にmakefile.soundが不足しているか、又は、自動生成に失敗しているのかなと思いました。
> [error.txt](https://github.com/zurachu/pceth2/files/1167914/error.txt)
> 
> 
> あと、mk.batを実行したPCにmake.exeが無い場合、別のエラーになるおそれもあるかな、と思いました。
> (P/ECE開発環境にPATHが通っていればmakeもあるはずなので杞憂かな・・・一応、念のため)

の対応。 P/ECE 開発環境じゃない make が使われると失敗の可能性もあると思いますので、バッチファイル形式での対応を検討してみましょうか。

**Comment by zurachu** [comment]
@nsawa #27 を試していただけないでしょうか。
#26 を適用しないと、ヒープのフラグメンテーションが激しくてバグる可能性がありますが、ひとまずSEデータはゲームデータに格納されて、音が鳴るようになるのではないかと思います。

**Comment by nsawa** [comment]
対応有難うございました。
最新のmk.batに置き換えてデータを変換したら、SE鳴るようになりました。


＃ 「Clone or download」のボタンでダウンロードすると、改行コードがLFになるのですね。
＃ 最初、mk.batが動かなくて焦りました…　CR+LFに変換すると、問題なく実行できました。
